### ISSUE TITLE
view_as_real is only supported for complex tensors

### ISSUE THREAD

**Issue by SEMLLYCAT** [sungwon23/BSRNN#1]
Hello! I tried to change the code to dp training form and found this problem
in: module.py line40. I printed the input tensor for model and found that the data form of dp multi-GPU is different from the original single GPU

**Comment by sungwon23** [comment]
In module.py, The input is supposed to be complex tensor (spectogram) . If i understand your comment correctly, you can drag out the view_as_real part and change on any demand as long as that tensor is the input spectrogram.
