### ISSUE TITLE
reproductioin

### ISSUE THREAD

**Issue by Janeliao-C** [sungwon23/BSRNN#5]
Hello，thank you for your sharing and generous！
But I got a problem when I reproduct your result with totally the same code. I use VoiceBank+Demand dataset , sampling rate 16kHz. And I split the 28 speakers in the trainset into train and test for 26 and 2 spkears ,respectively. I set batch  size as 18, and train epoch 100 in total.
When I test the model in VoiceBank+Demand testset, BUT I got PESQ at 1.97, STOI 0.92, it's weird and just like the model doesn't has been trained. Are you use the same testset in train and test? Or can you share your opinion about this question? 
Thanks a lot.

**Comment by sungwon3** [comment]
PESQ Score on noisy data is 1.97. It seems to me when you calculate the pesq score, it is calculated by using noisy and clean data.
 if weights of the network are multiplied by input somehow, I think the chance of getting a score of 1.97 is highly unlikely.

**Comment by Janeliao-C** [comment]
Sorry to bother you agian. I can't get a result totally the same as yours. PESQ 3.07, CSIG 4.48, CBAK 3.68, CVOL 3.85, SSNR 9.55, STOI 0.95 is my best result. All of them had an error less than 1.5%, But  I still wonder how do you look at this issue, is this a normal error?

**Comment by sungwon3** [comment]
Code doesn't involve fixed random seed generation. This can affect weight initialization, ergo the training process. That amount of variation can happen, and it happened sometime in my reproduction trail.
